services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: local
    volumes:
      - nvvt-mongo:/data/db

volumes:
  nvvt-mongo: